### ISSUE TITLE
Issue with reading roster

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/dmsky#22]
I am finding a strange error with the DM pipeline I using that is built with the dmsky, dmpipe, gammapy and fermipy packages.
The error deals with the creation of the folders and yaml files for the configuration of the analysis and astrophysical profiles

This is the error message:
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Using /nfs/slac/kipac/fs1/u/mdimauro/software/dmsky/dmsky/data for FileLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/data for FileLibrary
Path /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/data does have any subdirectories
Using /nfs/slac/kipac/fs1/u/mdimauro/software/dmsky/dmsky/data/targets for TargetLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/targets for TargetLibrary
Using /nfs/slac/kipac/fs1/u/mdimauro/software/dmsky/dmsky/data/rosters for RosterLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/rosters for RosterLibrary
Warning: <class 'dmsky.targets.Dwarf'> does not have attribute extension
Warning: <class 'dmsky.targets.Dwarf'> does not have attribute extsigma
Warning: <class 'dmsky.targets.Dwarf'> does not have attribute extension
Warning: <class 'dmsky.targets.Dwarf'> does not have attribute extsigma
Writing segue_1:ack2016
Traceback (most recent call last):
  File "/u/gl/mdimauro/kipac/software/anaconda/envs/dmpipe-test/bin/dmpipe-prepare-targets", line 33, in <module>
    sys.exit(load_entry_point('dmpipe', 'console_scripts', 'dmpipe-prepare-targets')())
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/jobs/link.py", line 310, in main
    link.run_analysis(sys.argv[1:])
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/dmpipe/dmpipe/dm_prepare.py", line 454, in run_analysis
    sims, args.spatial_models, aliases)
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/dmpipe/dmpipe/dm_prepare.py", line 340, in _write_target_dirs
    cls._write_astro_value_yaml(target, astro_val_path)
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/dmpipe/dmpipe/dm_prepare.py", line 233, in _write_astro_value_yaml
    astro_profile_data = target.profile.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
Timestamp: 1617103039
Exited with exit code 1

Usually this part returns the following message:
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Using /nfs/slac/kipac/fs1/u/dmcat/software/anaconda3_nfs/envs/dmpipe-test/lib/python3.7/site-packages/dmsky-0.2.5-py3.7.egg/dmsky/data for FileLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/data for FileLibrary
Path /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/data does have any subdirectories
Using /nfs/slac/kipac/fs1/u/dmcat/software/anaconda3_nfs/envs/dmpipe-test/lib/python3.7/site-packages/dmsky-0.2.5-py3.7.egg/dmsky/data/targets for TargetLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/targets for TargetLibrary
Using /nfs/slac/kipac/fs1/u/dmcat/software/anaconda3_nfs/envs/dmpipe-test/lib/python3.7/site-packages/dmsky-0.2.5-py3.7.egg/dmsky/data/rosters for RosterLibrary
Using /u/ek/echarles/dmcat_nfs/workdir/sandbox/dmpipe_example/dmsky_data/rosters for RosterLibrary

So something goes wrong when trying to read the roster.
You can find the example of my run in the file attached.
[dmpipe_example.zip](https://github.com/fermiPy/dmsky/files/6324750/dmpipe_example.zip)

**Comment by kadrlica** [comment]
@eacharles I've checked, and this issue does not occur for `pymodeler` `5ee4597`. I think something is going wrong with how the `Model` constructor is dealing with kwargs that are themselves dicts. I'll open an issue in pymodeler. 

Semi-minimal test example:
```
import dmsky.targets

kwargs = {'name': 'ursa_minor', 'abbr': 'UMi', 'title': 'Ursa Minor', 'version': 'default', 'color': 'red',
          'profile': {'type': 'NFW'},
          # I think these keywords are unnecessary
          'dec': 67.2225, 'ra': 227.2854,
          'distance': 76.0, 'dsigma': 3.0, 'abs_mag': -8.8, 'major_axis': 8.2, 'ellipticity': 0.56}

target = dmsky.targets.Target(**kwargs)
print("Profile")
print(target.profile)
```
In the older pymodeler this prints:
```
Profile
{'type': 'NFW'}
```
In the new pymodeler this prints
```
Profile
None
```

**Comment by kadrlica** [comment]
I believe this was resolved by the update to pymodeler.
